### ISSUE TITLE
Polling question

### ISSUE THREAD

**Issue by Deleplace** [davecheney/presentations#8]
Hello, this is a question about "Writing High Performance Go", please feel free to close immediately.

Slide #39 says "Go uses efficient polling, sometimes"

I'm not familiar with OS-level mechanisms, so I'd like to know if this slide is about : 

- **polling**, in the sense "the runtime or the os continually interrogates a peripheral device (network, local file) to see if it has data to transfer"
- or **pooling**, in the sense "the runtime manages a pool of objects, which allows thousands of goroutines to operate on a limited number of threads or file descriptors or other system resources"

Thanks again for the whole talk!

**Comment by Deleplace** [comment]
Slide link : http://talks.godoc.org/github.com/davecheney/presentations/writing-high-performance-go.slide#39

**Comment by davecheney** [comment]
Polling, like poll(2)

**Comment by Deleplace** [comment]
Thanks!
